import {useEffect, useState} from 'react'
import Head from 'next/head'
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import BooksTable from '../components/BooksTable'
import AuthorInfo from '../components/AuthorInfo'
import PopularAuthorsList from '../components/PopularAuthorsList';
import NavBar from '../components/NavBar';
import { getAuthor, getAuthorWorks } from '../utils/api/authors';


export default function Home() {
  const [authorKey, setAuthorKey] = useState("OL23919A")
  const [authorData, setAuthorData] = useState({})
  const [authorWorks, setAuthorWorks] = useState([])

  useEffect(()=> {
    getAuthor(authorKey).then((data)=> {
      setAuthorData(data)
    })
  }, [authorKey])

  useEffect(()=> {
    getAuthorWorks(authorKey).then((data)=> {
      console.log(data)
      setAuthorWorks(data)
    })
  }, [authorKey])

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <NavBar />
      <main>
        <Container maxWidth="md">
          <Grid container spacing={4}>
            <Grid item xs={8}>
              <Box>
                <AuthorInfo author={authorData} />
                <BooksTable books={authorWorks} />
              </Box>
            </Grid>
            <Grid item xs={4}>
              <PopularAuthorsList setAuthorKey={setAuthorKey}/>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  )
}
